### PR TITLE
Features

### PR DESCRIPTION
**Pull request by SigmaSam**
Add Jest as a TDD.
Included test for not rendering functions.

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SigmaSam and @julian3493  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] All of the functions should be tested, for example the following functions are not tested yet:
 => You are missing tests for the following functions `addNewChore, saveLocalChore, saveLocalGroup, addNewGroup, removeChore, editChore, project, filter, cleanGrid,`
- [ ] There are a lot of methods from other files which are not yet tested, kindly take your time and test all of the methods(functions) from all of the files
# [Optional changes] :yellow_circle: 
- [ ] You can setup tests to run on github actions
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by SigmaSam** [comment]
- Created test for the missing functions.
- The functions defined outside the List and Function files are only there to render the HTML or the website and we are not sure if it is necessary to test those or how to do it if so.

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [x] You have to test all of your functions so you also need to add tests for the following functions:

- `addNewChore`
- `addNewGroup`

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by SigmaSam** [comment]
Those two functions particularly just make call backs to `addChore` and `addGroup` respectively and don't really have any logic, just were build like that because we decided to create the whole HTML site using JavaScript, and therefore we needed an additional function at the time to call the `addEventListener`.

We tried to create test for them but Jest does not work the same with the DOM as we are used to so we can't "render" the HTML inside the test files to really test those functions.

Nevertheless if you know of a way how to do it please guide us on how to, thanks for your time.

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request closed without merging**
